import React from "react";
import { ICON_DATA, THEME_ICONS, ICON_ORDER } from "./statIconData.js";

// Stat icons for the `icons` treatment. Icon PATHS are baked from real lucide
// data (statIconData.js, generated by scripts/gen-stat-icons.mjs) so the export
// carries no runtime lucide dependency. Each theme has several distinct icons;
// assignStatIcons() dedupes across a section so a set of stats never shows the
// same icon twice — no AI, just keyword→theme matching plus a no-repeat pass.

// label THEME → matcher, first match wins. Ordered so specific themes (schools,
// corporations) beat the generic money bucket, which otherwise swallows any
// report that mentions dollars.
const RULES = [
  [/school|educat|\blearn|teacher|classroom|student|literac|graduat|curricul|pupil/, "education"],
  [/corporat|compan|business|\bceo\b|shareholder|\bfirm|industr|monopol|factor|manufactur/, "work"],
  [/health|hospital|medical|patient|nurse|doctor|mental|disease|mortalit|\bcare\b/, "health"],
  [/climate|carbon|emission|greenhouse|environment|\benergy|pollut|warming|renewable|forest|\btree/, "climate"],
  [/\bhome\b|housing|shelter|\brent\b|mortgage|tenant|homeowner|\bhouse|apartment/, "housing"],
  [/government|policy|\bstate\b|govern|\bnation|\blaw\b|justice|court|democra|\bvote|elect|legislat/, "gov"],
  [/food|farm|agricultur|\bcrop|hunger|nutrit|harvest|grain|\bmeal/, "food"],
  [/water|ocean|river|drought|drink|\bsea\b|marine|coastal/, "water"],
  [/global|world|countr|internationa|planet|\bmap\b|migrat|border/, "global"],
  [/\bjob|employ|\bwork|labou?r|staff|workforce|worker|occupation/, "work"],
  [/\$|money|wealth|dollar|\btn\b|\bbn\b|\bpay\b|income|\bcost|\bfund|invest|gdp|financ|profit|salar|wage|earn|revenue|budget|\bdebt|\bloan/, "money"],
  [/people|population|\bchildren|\bwomen|\bmen\b|household|famil|adult|resident|citizen|individual|person|communit/, "people"],
  [/increas|\bgrow|\brise|rising|surg|doubl|higher|expand|\bup\b|more\b/, "up"],
  [/declin|decreas|\bfall|\bdrop|\bloss|\blost|lower|reduc|shrink|fewer/, "down"],
  [/power|electric|\bgrid|\bfuel|\bgas\b|\boil\b|solar|battery/, "energy"],
  [/data|digital|softwar|comput|technolog|\bai\b|internet|online|cyber/, "tech"],
];

const strip = (s) => String(s || "").replace(/<[^>]+>/g, " ");

// Ordered icon candidates for one stat (best first). The value's own unit is the
// strongest signal (476 YEARS → time, $105tn → money), then any alarm word, then
// the label's theme, then a generic bucket. Returns lucide names, all present in
// ICON_DATA.
export function iconCandidates(value, label) {
  const v = String(value || "").toLowerCase();
  const text = `${v} ${strip(label)}`.toLowerCase();
  const lists = [];
  const push = (theme) => { if (THEME_ICONS[theme]) lists.push(THEME_ICONS[theme]); };

  // value unit leads
  if (/\d[\d.,]*\s*(years?|yrs?|days?|hours?|months?|decades?|weeks?)\b/.test(v)) push("time");
  if (/[$£€]|\d[\d.,]*\s*(tn|bn|trillion|billion|million)\b/.test(v)) push("money");
  // alarming stats
  if (/traum|abuse|violen|suspend|expel|crisis|homeless|insecur|death|\bdied|kill/.test(text)) push("alert");
  // label theme
  for (const [re, theme] of RULES) if (re.test(text)) { push(theme); break; }
  // percent + generic tail
  if (/%|percent/.test(v)) lists.push(["percent"]);
  push("generic");

  // flatten, de-dupe, keep only baked icons
  const out = [];
  const seen = new Set();
  for (const list of lists) for (const n of list) {
    if (ICON_DATA[n] && !seen.has(n)) { seen.add(n); out.push(n); }
  }
  return out.length ? out : ["circle-dot"];
}

// Assign a DISTINCT icon to each card in a section: each stat takes the first of
// its own candidates not yet used; if those are exhausted, the next unused icon
// from the global order; only if the section has more stats than we have icons
// (137) does anything repeat. Deterministic — stable across renders.
export function assignStatIcons(cards) {
  const used = new Set();
  const take = (names) => {
    for (const n of names) if (ICON_DATA[n] && !used.has(n)) { used.add(n); return n; }
    return null;
  };
  return (cards || []).map((c) => {
    const cands = iconCandidates(c.value, c.label);
    return take(cands) || take(ICON_ORDER) || cands[0] || "circle-dot";
  });
}

// single best icon for a stat (standalone use, no de-dupe context)
export const pickStatIcon = (value, label) => iconCandidates(value, label)[0];

export function StatIcon({ value, label, name, size = "1.35em" }) {
  const key = (name && ICON_DATA[name]) ? name : pickStatIcon(value, label);
  const data = ICON_DATA[key] || ICON_DATA["circle-dot"];
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor"
      strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"
      style={{ display: "block", flex: "none" }}>
      {(data || []).map(([tag, attrs], i) => React.createElement(tag, { key: i, ...attrs }))}
    </svg>
  );
}
